### ISSUE TITLE
FATAL  Package subpath './nuxt' is not defined by "exports"

### ISSUE THREAD

**Issue by HendrikJan** [posva/pinia#1021]
### Reproduction

https://codesandbox.io/s/nuxt-bridge-pinia-error-heowb?file=/sandbox.config.json

### Steps to reproduce the behavior

1. Go to https://codesandbox.io/s/nuxt-bridge-pinia-error-heowb?file=/sandbox.config.json
2. Restart the codesandbox server (maybe you have to fork the sandbox before you are allowed to restart the server, I don't know)
3. See error in codesandbox terminal:

```
Nuxt config loading...                                                08:15:55

 FATAL  Package subpath './nuxt' is not defined by "exports" in /sandbox/node_modules/pinia/package.json

  at new NodeError (internal/errors.js:322:7)
  at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
  at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
  at resolveExports (internal/modules/cjs/loader.js:450:36)
  at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
  at Function.resolve (internal/modules/cjs/helpers.js:99:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:192625)
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:194612)
  at Resolver.requireModule (node_modules/@nuxt/core-edge/dist/core.js:274:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:129:38)
  at node_modules/@nuxt/utils-edge/dist/utils.js:497:61
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)
```

### Expected behavior

The error should not be there.
The application should be visible.

### Actual behavior

There is the error.
The application does not show (Codesandbox says: "This page could not be found" or "502: Bad Gateway")

### Additional information

* If I remove Pinia there is no error
* I thought that the problem might have to do with using `srcDir`, but when removing `srcDir` the error is still there.

**Comment by LinusBorg** [comment]
You just have a typo in your nuxt config.

```diff
- buildModules: ["pinia/nuxt", "@nuxtjs/vuetify"],
+ buildModules: ["@pinia/nuxt", "@nuxtjs/vuetify"],

**Comment by HendrikJan** [comment]
Thanks a lot!
