### ISSUE TITLE
Document build failure

### ISSUE THREAD

**Issue by linjialiang** [posva/pinia#1251]
### Reproduction

Document build failure

### Steps to reproduce the bug

Document build failure

### Expected behavior

Document build failure

### Actual behavior

Document build failure

### Additional information

Document build failure

**Comment by linjialiang** [comment]
```powershell
vitepress v0.22.3
⠸ building client + server bundles...[vite:vue] Duplicate attribute.
file: D:/site/vue3doc/pinia/packages/docs/api/modules/pinia.md:700:68
✖ building client + server bundles...
build error:
 Error [SyntaxError]: Duplicate attribute.
    at createCompilerError (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:18:19)
    at emitError (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1566:29)
    at parseAttribute (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1310:9)
    at parseAttributes (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1286:22)
    at parseTag (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1175:17)
    at parseElement (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1104:21)
    at parseChildren (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:933:28)
    at parseElement (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1120:22)
    at parseChildren (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:933:28)
    at parseElement (D:\site\vue3doc\pinia\node_modules\.pnpm\@vue+compiler-core@3.2.31\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1120:22) {
  id: 'D:/site/vue3doc/pinia/packages/docs/api/modules/pinia.md',
  plugin: 'vite:vue',
  loc: {
    file: 'D:/site/vue3doc/pinia/packages/docs/api/modules/pinia.md',
    line: 700,
    column: 68
  },
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  watchFiles: [
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/index.js',
    'D:/site/vue3doc/pinia/packages/docs/api/enums/pinia.MutationType.md',
    'D:/site/vue3doc/pinia/packages/docs/api/index.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.DefineSetupStoreOptions.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.DefineStoreOptions.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.DefineStoreOptionsBase.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.DefineStoreOptionsInPlugin.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.MapStoresCustomization.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.Pinia.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.PiniaCustomProperties.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.PiniaCustomStateProperties.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.PiniaPlugin.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.PiniaPluginContext.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.StoreDefinition.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.StoreProperties.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.SubscriptionCallbackMutationDirect.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.SubscriptionCallbackMutationPatchFunction.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia.SubscriptionCallbackMutationPatchObject.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia._StoreOnActionListenerContext.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia._StoreWithState.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia._SubscriptionCallbackMutationBase.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia_testing.TestingOptions.md',
    'D:/site/vue3doc/pinia/packages/docs/api/interfaces/pinia_testing.TestingPinia.md',
    'D:/site/vue3doc/pinia/packages/docs/api/modules/pinia.md',
    'D:/site/vue3doc/pinia/packages/docs/api/modules/pinia_testing.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/composing-stores.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/hot-module-replacement.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/index.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/migration-0-0-7.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/migration-v1-v2.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/migration-vuex.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/options-api.md',
    'D:/site/vue3doc/pinia/packages/docs/cookbook/testing.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/actions.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/getters.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/index.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/outside-component-usage.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/plugins.md',
    'D:/site/vue3doc/pinia/packages/docs/core-concepts/state.md',
    'D:/site/vue3doc/pinia/packages/docs/getting-started.md',
    'D:/site/vue3doc/pinia/packages/docs/index.md',
    'D:/site/vue3doc/pinia/packages/docs/introduction.md',
    'D:/site/vue3doc/pinia/packages/docs/ssr/index.md',
    'D:/site/vue3doc/pinia/packages/docs/ssr/nuxt.md',
    'plugin-vue:export-helper',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vue@3.2.31/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/utils.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/router.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/data.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/composables/head.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/composables/preFetch.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/components/Content.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/components/ClientOnly.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/composables/preFetch.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/components/Content.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/components/ClientOnly.js',
    'D:/site/vue3doc/pinia/node_modules/.pnpm/vitepress@0.22.3/node_modules/vitepress/dist/client/app/components/Debug.vue',
    'D:/site/vue3doc/pinia/packages/docs/.vitepress/theme/index.js'
  ]
}
D:\site\vue3doc\pinia\packages\docs:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @pinia/docs@0.0.0 docs:build: `vitepress build .`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by linjialiang** [comment]
![图片](https://user-images.githubusercontent.com/8848263/164980761-c52524c3-abb4-4d4e-a338-07e2c28f5b4a.png)

> This write version control should be removed

**Comment by linjialiang** [comment]
> There is no such file

![图片](https://user-images.githubusercontent.com/8848263/164980843-2336ae6b-a9f0-4589-a937-059679e9648d.png)

**Comment by linjialiang** [comment]
> The developers on your team also wrote a TODO

![图片](https://user-images.githubusercontent.com/8848263/164981206-2347d728-ebcd-4356-aabb-2bcabbee551b.png)

**Comment by posva** [comment]
Doc build is working. API files were temporarily kept ats own point for reasons

**Comment by linjialiang** [comment]
> @posva Since I often cannot access the Internet normally, could you provide `gh-pages` branch 
Thank you very much

**Comment by linjialiang** [comment]
> The build error was caused by some of these 33 lines

path:  `pinia/packages/docs/api/modules/pinia.md` 

```md
Ƭ **PiniaStorePlugin**: [`PiniaPlugin`](../interfaces/pinia.PiniaPlugin.md)

Ƭ **StateTree**: `Record`<`string` \| `number` \| `symbol`, `any`\>

Ƭ **Store**<`Id`, `S`, `G`, `A`\>: [`_StoreWithState`](../interfaces/pinia._StoreWithState.md)<`Id`, `S`, `G`, `A`\> & `UnwrapRef`<`S`\> & [`_StoreWithGetters`](pinia.md#_storewithgetters)<`G`\> & [`_ActionsTree`](pinia.md#_actionstree) extends `A` ? {} : `A` & [`PiniaCustomProperties`](../interfaces/pinia.PiniaCustomProperties.md)<`Id`, `S`, `G`, `A`\> & `PiniaCustomStateProperties`<`S`\>

Ƭ **StoreActions**<`SS`\>: `SS` extends [`Store`](pinia.md#store)<`string`, [`StateTree`](pinia.md#statetree), [`_GettersTree`](pinia.md#_getterstree)<[`StateTree`](pinia.md#statetree)\>, infer A\> ? `A` : [`_ExtractActionsFromSetupStore`](pinia.md#_extractactionsfromsetupstore)<`SS`\>

Ƭ **StoreGeneric**: [`Store`](pinia.md#store)<`string`, [`StateTree`](pinia.md#statetree), [`_GettersTree`](pinia.md#_getterstree)<[`StateTree`](pinia.md#statetree)\>, [`_ActionsTree`](pinia.md#_actionstree)\>

Ƭ **StoreGetters**<`SS`\>: `SS` extends [`Store`](pinia.md#store)<`string`, [`StateTree`](pinia.md#statetree), infer G, [`_ActionsTree`](pinia.md#_actionstree)\> ? [`_StoreWithGetters`](pinia.md#_storewithgetters)<`G`\> : [`_ExtractGettersFromSetupStore`](pinia.md#_extractgettersfromsetupstore)<`SS`\>

Ƭ **StoreOnActionListener**<`Id`, `S`, `G`, `A`\>: (`context`: [`StoreOnActionListenerContext`](pinia.md#storeonactionlistenercontext)<`Id`, `S`, `G`, {} extends `A` ? [`_ActionsTree`](pinia.md#_actionstree) : `A`\>) => `void`

Ƭ **StoreOnActionListenerContext**<`Id`, `S`, `G`, `A`\>: [`_ActionsTree`](pinia.md#_actionstree) extends `A` ? [`_StoreOnActionListenerContext`](../interfaces/pinia._StoreOnActionListenerContext.md)<[`StoreGeneric`](pinia.md#storegeneric), `string`, [`_ActionsTree`](pinia.md#_actionstree)\> : { [Name in keyof A]: Name extends string ? \_StoreOnActionListenerContext<Store<Id, S, G, A\>, Name, A\> : never }[keyof `A`]

Ƭ **StoreState**<`SS`\>: `SS` extends [`Store`](pinia.md#store)<`string`, infer S, [`_GettersTree`](pinia.md#_getterstree)<[`StateTree`](pinia.md#statetree)\>, [`_ActionsTree`](pinia.md#_actionstree)\> ? `UnwrapRef`<`S`\> : [`_ExtractStateFromSetupStore`](pinia.md#_extractstatefromsetupstore)<`SS`\>

Ƭ **SubscriptionCallback**<`S`\>: (`mutation`: [`SubscriptionCallbackMutation`](pinia.md#subscriptioncallbackmutation)<`S`\>, `state`: `UnwrapRef`<`S`\>) => `void`

Ƭ **SubscriptionCallbackMutation**<`S`\>: [`SubscriptionCallbackMutationDirect`](../interfaces/pinia.SubscriptionCallbackMutationDirect.md) \| [`SubscriptionCallbackMutationPatchObject`](../interfaces/pinia.SubscriptionCallbackMutationPatchObject.md)<`S`\> \| [`SubscriptionCallbackMutationPatchFunction`](../interfaces/pinia.SubscriptionCallbackMutationPatchFunction.md)

Ƭ **\_ActionsTree**: `Record`<`string`, [`_Method`](pinia.md#_method)\>

Ƭ **\_Awaited**<`T`\>: `T` extends ``null`` \| `undefined` ? `T` : `T` extends `object` & { `then`: (`onfulfilled`: `F`) => `any`  } ? `F` extends (`value`: infer V, ...`args`: `any`) => `any` ? [`_Awaited`](pinia.md#_awaited)<`V`\> : `never` : `T`

Ƭ **\_DeepPartial**<`T`\>: { [K in keyof T]?: \_DeepPartial<T[K]\> }

Ƭ **\_ExtractActionsFromSetupStore**<`SS`\>: `SS` extends `undefined` \| `void` ? {} : [`_ExtractActionsFromSetupStore_Keys`](pinia.md#_extractactionsfromsetupstore_keys)<`SS`\> extends keyof `SS` ? `Pick`<`SS`, [`_ExtractActionsFromSetupStore_Keys`](pinia.md#_extractactionsfromsetupstore_keys)<`SS`\>\> : `never`

Ƭ **\_ExtractActionsFromSetupStore\_Keys**<`SS`\>: keyof { [K in keyof SS as SS[K] extends \_Method ? K : never]: any }

Ƭ **\_ExtractGettersFromSetupStore**<`SS`\>: `SS` extends `undefined` \| `void` ? {} : [`_ExtractGettersFromSetupStore_Keys`](pinia.md#_extractgettersfromsetupstore_keys)<`SS`\> extends keyof `SS` ? [`_UnwrapAll`](pinia.md#_unwrapall)<`Pick`<`SS`, [`_ExtractGettersFromSetupStore_Keys`](pinia.md#_extractgettersfromsetupstore_keys)<`SS`\>\>\> : `never`

Ƭ **\_ExtractGettersFromSetupStore\_Keys**<`SS`\>: keyof { [K in keyof SS as SS[K] extends ComputedRef ? K : never]: any }

Ƭ **\_ExtractStateFromSetupStore**<`SS`\>: `SS` extends `undefined` \| `void` ? {} : [`_ExtractStateFromSetupStore_Keys`](pinia.md#_extractstatefromsetupstore_keys)<`SS`\> extends keyof `SS` ? [`_UnwrapAll`](pinia.md#_unwrapall)<`Pick`<`SS`, [`_ExtractStateFromSetupStore_Keys`](pinia.md#_extractstatefromsetupstore_keys)<`SS`\>\>\> : `never`

Ƭ **\_ExtractStateFromSetupStore\_Keys**<`SS`\>: keyof { [K in keyof SS as SS[K] extends \_Method \| ComputedRef ? never : K]: any }

Ƭ **\_GettersTree**<`S`\>: `Record`<`string`, (`state`: `UnwrapRef`<`S`\> & `UnwrapRef`<`PiniaCustomStateProperties`<`S`\>\>) => `any` \| () => `any`\>

Ƭ **\_MapActionsObjectReturn**<`A`, `T`\>: { [key in keyof T]: A[T[key]] }

Ƭ **\_MapActionsReturn**<`A`\>: { [key in keyof A]: A[key] }

Ƭ **\_MapStateObjectReturn**<`Id`, `S`, `G`, `A`, `T`\>: { [key in keyof T]: Function }

Ƭ **\_MapStateReturn**<`S`, `G`, `Keys`\>: { [key in Keys]: Function }

Ƭ **\_MapWritableStateObjectReturn**<`S`, `T`\>: { [key in keyof T]: Object }

Ƭ **\_MapWritableStateReturn**<`S`\>: { [key in keyof S]: Object }

Ƭ **\_Method**: (...`args`: `any`[]) => `any`

Ƭ **\_Spread**<`A`\>: `A` extends [infer L, ...infer R] ? [`_StoreObject`](pinia.md#_storeobject)<`L`\> & [`_Spread`](pinia.md#_spread)<`R`\> : `unknown`

Ƭ **\_StoreObject**<`S`\>: `S` extends [`StoreDefinition`](../interfaces/pinia.StoreDefinition.md)<infer Ids, infer State, infer Getters, infer Actions\> ? { [Id in \`${Ids}${MapStoresCustomization extends Record<"suffix", string\> ? MapStoresCustomization["suffix"] : "Store"}\`]: Function } : {}

Ƭ **\_StoreWithActions**<`A`\>: { [k in keyof A]: A[k] extends Function ? Function : never }

Ƭ **\_StoreWithGetters**<`G`\>: { readonly [k in keyof G]: G[k] extends Function ? R : UnwrapRef<G[k]\> }

Ƭ **\_UnwrapAll**<`SS`\>: { [K in keyof SS]: UnwrapRef<SS[K]\> }
```
