### ISSUE TITLE
Warn when Getter with same name as State

### ISSUE THREAD

**Issue by bitmage** [posva/pinia#1331]
### Reproduction

https://github.com/TorchlightSoftware/nuxt-bugs/tree/pinia-getter-state-conflict

### Steps to reproduce the bug

Create a getter with the same name as a property in the state.

```ts
import {defineStore} from 'pinia'

export const useAuthStore = defineStore('auth', {
  state: () => ({
    user: {fname: 'Donna', lname: 'Renolds'},
  }),

  getters: {
    user: (state) => state.user,
  },

  actions: {
  },
})

```

### Expected behavior

This should produce an error telling the application developer not to do this.

### Actual behavior

When the value is consumed, it overflows the stack:

```
[nuxt] [request error] Maximum call stack size exceeded
  at formatRaw (node:internal/util/inspect:1037:12)  
  at formatValue (node:internal/util/inspect:817:10)  
  at inspect (node:internal/util/inspect:347:10)  
  at formatWithOptionsInternal (node:internal/util/inspect:2167:40)  
  at formatWithOptions (node:internal/util/inspect:2029:10)  
  at console.value (node:internal/console/constructor:324:14)  
  at console.log (node:internal/console/constructor:360:61)  
  at Proxy.me (./.nuxt/dist/server/server.mjs:2956:15)  
  at ReactiveEffect.fn (./node_modules/pinia/dist/pinia.mjs:1159:38)  
  at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
```

### Additional information

Beginner mistake, not understanding that the getter is unnecessary in this case.  A clear error message would save time and help to more quickly determine the cause.  Thanks!

**Comment by posva** [comment]
Contribution for a dev only warning!
