### ISSUE TITLE
Nux3 - inject is not a function

### ISSUE THREAD

**Issue by tasiotas** [posva/pinia#1428]
### Reproduction

none

### Steps to reproduce the bug

package.json

```{
  "private": true,
  "scripts": {
    "dev": "nuxi dev --https --ssl-cert ../certs/example.com+5.pem --ssl-key ../certs/example.com+5-key.pem",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@iconify/json": "^2.1.73",
    "@unocss/nuxt": "^0.43.2",
    "@vueuse/core": "^8.9.0",
    "@vueuse/nuxt": "^8.9.0",
    "nuxt": "npm:nuxt3@latest",
    "sass": "^1.53.0"
  },
  "dependencies": {
    "@inkline/inkline": "^3.0.9",
    "@inkline/nuxt": "3.1.4",
    "@pinia/nuxt": "^0.1.9",
    "@vueuse/integrations": "^8.9.0",
    "nuxt-graphql-client": "^0.0.33",
    "pinia": "^2.0.14"
  }
}
```

### Expected behavior

run Pinia in Nuxt3

### Actual behavior

```
[nuxt] [request error] inject is not a function
  at PiniaNuxtPlugin (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:30966:3)      
  at fn (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:571:27)
  at Object.callAsync (/C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:573:23)
  at applyPlugin (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:540:29)
  at Module.applyPlugins (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:550:11)
  at async createNuxtAppServer (/C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (/C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)       
  at async /C:/Work/xxx/Website/Code/xxx/Frontend/.nuxt/dev/index.mjs:473:20
  at async /C:/Work/xxx/Website/Code/xxx/Frontend/node_modules/h3/dist/index.mjs:420:19     ```

### Additional information

Hi,

Sorry for nor providing repro, but so far I cannot get any errors when I try it on Stackblitz. So it must be something in my project.

Basicall I follow those steps:
1. `yarn add pinia @pinia/nuxt` - im on Nuxt3
2. add `modules: ['@pinia/nuxt']` in nuxt.config.ts
3. Then Immediately I get the error. If I remove Pinia from modules, Its back to normal.

Any clues what might be going on?

Thank you

**Comment by tasiotas** [comment]
all good, its because of having latest nuxt, instead of RC.

bad
```"nuxt": "npm:nuxt3@latest"```

good
```"nuxt": "3.0.0-rc.4"```

**Comment by Luffyyy** [comment]
It's still an issue waiting to be fixed since rc 5 or production will have it.

> If you are using plugins (perhaps injected by a module) that are relying on the Nuxt 2 format of (context, inject) => void then it needs to be updated to the new Nuxt 3 format of (nuxtApp) => void: https://v3.nuxtjs.org/guide/directory-structure/plugins#creating-plugins

Code that seems to rely on this:
https://github.com/vuejs/pinia/blob/4a9835e4695d4cb49c2279bb5d0f80c60cee2bff/packages/nuxt/src/templates/plugin.ts#L12

https://github.com/nuxt/framework/pull/5630
