### ISSUE TITLE
 ERROR  hasInjectionContext  when building my Nuxt 3 project

### ISSUE THREAD

**Issue by nieuwsvertaald** [posva/pinia#2218]
**FIXED**

The guide only said to install "pinia/nuxt", but after I also installed "pinia" it worked.

### Reproduction

Can't do that due to data

### Steps to reproduce the bug

I run the command "pnpm run build" to build my project

### Expected behavior

Would expect my project to build without errors

### Actual behavior

Building gets cancelled and returns this error:

```
 ERROR  "hasInjectionContext" is not exported by "node_modules/.pnpm/nuxt@3.4.2_@types+node@18.15.12/node_modules/nuxt/dist/app/compat/vue-demi.js", imported by "node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs".                                                              4:42:41 PM
file: D:/Websites/website/node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs:6:9
4:   * @license MIT
5:   */
6: import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set,...
            ^
7: import { setupDevtoolsPlugin } from '@vue/devtools-api';


 ERROR  "hasInjectionContext" is not exported by "node_modules/.pnpm/nuxt@3.4.2_@types+node@18.15.12/node_modules/nuxt/dist/app/compat/vue-demi.js", imported by "node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs".                                                              4:42:41 PM  

  at error (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Module.error (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:13334:16)
  at Module.traceVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:13719:29)
  at ModuleScope.findVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:12234:39)
  at ReturnValueScope.findVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:6974:38)
  at Identifier.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:8124:40)
  at CallExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)
  at CallExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:9653:15)
  at LogicalExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)
  at LogicalExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)

 ELIFECYCLE  Command failed with exit code 1.
```

Nuxt 3.4.2 with Pinia 0.4.11

### Additional information

 ERROR  "hasInjectionContext" is not exported by "node_modules/.pnpm/nuxt@3.4.2_@types+node@18.15.12/node_modules/nuxt/dist/app/compat/vue-demi.js", imported by "node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs".                                                              4:42:41 PM
file: D:/Websites/nieuwsvertaald_nieuw/node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs:6:9
4:   * @license MIT
5:   */
6: import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set,...
            ^
7: import { setupDevtoolsPlugin } from '@vue/devtools-api';

 ERROR  "hasInjectionContext" is not exported by "node_modules/.pnpm/nuxt@3.4.2_@types+node@18.15.12/node_modules/nuxt/dist/app/compat/vue-demi.js", imported by "node_modules/.pnpm/pinia@2.1.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs".                                                              4:42:41 PM  

  at error (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Module.error (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:13334:16)
  at Module.traceVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:13719:29)
  at ModuleScope.findVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:12234:39)
  at ReturnValueScope.findVariable (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:6974:38)
  at Identifier.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:8124:40)
  at CallExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)
  at CallExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:9653:15)
  at LogicalExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)
  at LogicalExpression.bind (/D:/Websites/website/node_modules/.pnpm/rollup@3.20.6/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)

 ELIFECYCLE  Command failed with exit code 1.

Nuxt 3.4.2

**Comment by posva** [comment]
Looks like you need to update vue-demi with npm update vue-demi or similar. Shouldn't be related to pinia itself.

**Comment by pouzarm** [comment]
@posva I have same error using `yarn v1 / vite / not nuxt`. 

My `vue-demi` version in `yarn.lock/node_modules` is **0.14.5**. Same minimum as Pinia says, but the missing function isn't available, because it resolves the path for import to `node_modules/vue-demi/lib/index.mjs` which doesn't contain the function.

Only `index.mjs` in subfolders named **v2** and **v2.7** contains it.

**Comment by jahnli** [comment]
same

```
No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"
```

**Comment by posva** [comment]
Then you need to update Vue to 3.3 as the peer dependency requires

**Comment by BudiSalah** [comment]
Downgrade to `pinia@2.0.35`
