### ISSUE TITLE
Vue3 SSR mode error: The requested module vue-demi does not provide an export named 'hasInjectionContext'

### ISSUE THREAD

**Issue by aboutZZ** [posva/pinia#2228]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-eca2rc?file=src%2Fmain.ts

### Steps to reproduce the bug

Setup pinia in SSR mode:
```js
export function createApp() {
  const app = createSSRApp(App);
  const store = createPinia();
  app.use(store);
  return {
    app,
  };
}

```

### Expected behavior

Project run normally

### Actual behavior

Error in broswer console:
```js
15:24:44 [vite] page reload src/main.ts
✘ [ERROR] No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"

    node_modules/.pnpm/pinia@2.1.3_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9:
      6 │ import { hasInjectionContext, inject, toRaw, watch, unref, markRaw,...
        ╵          ~~~~~~~~~~~~~~~~~~~

15:24:44 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/pinia@2.1.3_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9: ERROR: No matching export in "node_modules/.pnpm/vue-demi@0.14.5_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"
    at failureErrorWithLog (/home/projects/vitejs-vite-eepwx6/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1626:15)
    at buildResponseToResult/< (/home/projects/vitejs-vite-eepwx6/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1038:44)
    at runOnEndCallbacks/< (/home/projects/vitejs-vite-eepwx6/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1502:13)
^C
```

### Additional information
Downgrade to version `2.0.23` everything works fine.

**Comment by posva** [comment]
You need to update vue to 3.3 as pointed out by the peer dependency.

**Comment by YUT4KA** [comment]
除了降低版本还有其他解决办法嘛，是将pinia降到了那个版本？

**Comment by df-5c** [comment]
同问，将pinia降到了那个版本合适？

**Comment by posva** [comment]
It's fine to stay on 2.0 until you can upgrade Vue to 3.3 but Vue 3.3 doesn't have any breaking changes so it should be fine to update too

**Comment by df-5c** [comment]
您好，来信已收到，我会尽快给您回复的。
