### ISSUE TITLE
Nuxt 3 Module install fails

### ISSUE THREAD

**Issue by sosensible** [posva/pinia#2467]
### Reproduction

.

### Steps to reproduce the bug

1. Install the current nuxt with DevTools
2. go to modules in devTools
3. install Pinia/Nuxt module
4. It installs, attempts to restart, and fails.

### Expected behavior

actually installs

### Actual behavior

Gives this message in the terminal.
``` 
nuxt.config.ts updated. Restarting nuxt...                                                                                                                                      10:14:51 AM
ℹ Using default Tailwind CSS file                                                                                                                                nuxt:tailwindcss 10:14:51 AM

 ERROR  Cannot restart nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                                                                            10:14:52 AM
Require stack:
- /home/dojo/dev/nuxt/wsl-nuxt/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:127:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:250334)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at setup (node_modules/@pinia/nuxt/dist/module.mjs:26:5)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:37)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3655:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev2.mjs:107:10)
  ```

### Additional information

Commenting out the module in nuxt.config.ts removes it.

**Comment by posva** [comment]
Please, report to devtools

**Comment by WalterKstro** [comment]
You need install pinia too 
`npm install pinia @pinia/nuxt`

And
If you're using npm, you might encounter an ERESOLVE unable to resolve dependency tree error. In that case, add the following to your package.json:
`"overrides": {
  "vue": "latest"
}`

**Comment by hecktarzuli** [comment]
I got this error just trying to install `@pinia/nuxt` for the first time via `npm`.  I was able to get it working after adding the `overrides` prop like above, but I did not need to install `pinia`.
