### ISSUE TITLE
No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "effectScope"

### ISSUE THREAD

**Issue by thespacedeck** [posva/pinia#590]
### Reproduction

I have following config:
```
"dependencies": {
    "pinia": "^2.0.0-beta.5",
    "vue": "^3.1.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.3.0",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.5",
    "postcss": "^8.3.0",
    "tailwindcss": "^2.2.2",
    "typescript": "^4.3.2",
    "vite": "^2.4.4",
    "vue-tsc": "^0.2.2"
  }
```
main.ts
```
import { createApp } from "vue";
import App from "./App.vue";
import { store } from "./store";

createApp(App)
  .use(store)
  .mount("#app");
```
store/index.ts
```
import { createPinia } from "pinia";
const store = createPinia();

export {
  store
};
```

### Steps to reproduce the behavior

1. $ npm i
2. $ npm run dev

### Expected behavior

Vue results in error:
```
error when starting dev server:
Error: Build failed with 1 error:
node_modules/pinia/dist/pinia.esm-browser.js:6:31: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "effectScope"
    at failureErrorWithLog (/......./node_modules/esbuild/lib/main.js:1449:15)
    at /......./node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/......./node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/......./node_modules/esbuild/lib/main.js:1129:7)
    at /......./node_modules/esbuild/lib/main.js:1236:14
    at /......./node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/......./node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/......./node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
```

Are the vue an Pina version not compatible...? Any help would be appreciated here.

Kind Regards,
Wzz

**Comment by jack-theripper** [comment]
Bug in 2.0.0-rc. 0. Use the hard-coded version 2.0.0-beta.5

**Comment by thalesagapito** [comment]
The effectScope API was just recently introduced (https://github.com/vuejs/vue-next/pull/2195). Try updating your vue version to at least ^3.2.0

**Comment by posva** [comment]
I explained this in the changelog 😉

**Comment by posva** [comment]
As some might come across this by simply installing Pinia for the first time, I created https://github.com/posva/pinia/issues/592. Comment there if you think anything is missing.
