### ISSUE TITLE
Problem with Pinia and latest build of Nuxt3

### ISSUE THREAD

**Issue by lukaszflorczak** [posva/pinia#730]
Today I updated Nuxt 3 to the latest release and Pinia stopped working. Here is the repository with a totally clear installation of Nuxt 3 (on `main` branch) and Pinia (on `test/pinia`):

https://github.com/lukaszflorczak/nuxt3-demo/tree/test/pinia

To reproduce the problem, just run the project. You should see:

<img width="1718" alt="Zrzut ekranu 2021-10-19 o 08 13 43" src="https://user-images.githubusercontent.com/1818979/137854622-c14f5cfc-5314-4414-a219-1176f209d2aa.png">

```
Accessing app is not supported in Nuxt3.
Cannot read properties of undefined (reading 'use')
  at PiniaNuxtPlugin (file://./.nuxt/dist/server/server.mjs:2053:17)  
  at file://./.nuxt/dist/server/server.mjs:201:27  
  at file://./.nuxt/dist/server/server.mjs:187:38  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:227:13)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:187:10)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:192:11)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:34:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:163:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:572:19)
```

Yesterday I tested Pinia on version `3.0.0-27242646.117b3aa` and it has worked yet.

**Comment by productdevbook** [comment]
some problem 
https://github.com/nuxt/nuxt.js/issues/12255

Reproduction

branch: use_bug
https://github.com/productdevbook/nuxt3-app/tree/use_bug

yarn dev

**Comment by productdevbook** [comment]
nuxtApp.app was renamed to nuxtApp.vueApp nuxt/bridge#302

**Comment by productdevbook** [comment]
why did you close this place, library needs to be updated ?

**Comment by lukaszflorczak** [comment]
Sorry, it was accidental. I allowed myself to create a PR.
